name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Sơn nhớ giữ dòng này để có nút bấm chạy tay nhé!

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.43.0-jammy

    # --- ĐÂY LÀ ĐOẠN CHIA SHARD ---
    strategy:
      fail-fast: false # Nếu 1 máy fail, các máy khác vẫn tiếp tục chạy
      matrix:
        shardIndex: [1, 2, 3] # Chạy 3 máy ảo
        shardTotal: [3]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run Playwright tests
        # Thêm flag --shard vào lệnh chạy
        # Nó sẽ chia file tests/post.test.ts ra các máy (nếu file này có nhiều test case)
        run: npx playwright test tests/ --project api --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          # Sơn ĐẶC BIỆT lưu ý: Tên artifact phải khác nhau ở mỗi máy
          name: playwright-report-${{ matrix.shardIndex }}
          path: playwright-report/
          retention-days: 30
